# Generated by Django 2.2.16 on 2022-04-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220408_1853'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_name_follower',
        ),
    ]
